services:
  postgres:
    image: "postgres:14.1-alpine"
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres

  nextjs:
    depends_on:
      - postgres
    restart: always
    build: .
    ports:
      - "3000:3000/upload"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
